import type { Metadata } from "next";
import { Play } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import { Header } from "@/widgets/Header";

const geistPlay = Play({
  variable: "--font-geist-play",
  subsets: ["latin"],
  weight: ["400",  "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistPlay.variable} ${styles.main}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
